language: node_js
node_js:
  - 7.6.0
  - 7.7.0
  - 7.7.1
  - 7.7.2
  - 7.7.3
  - 7.7.4
  - 7.8.0
  - 7.9.0
  - 7.10.0
  - 7.10.1
  - 8.0.0
  - 8.1.0
  - 8.1.1
  - 8.1.2
  - 8.1.3
  - 8.1.4
  - 8.2.0
  - 8.2.1
  - 8.3.0
  - 8.4.0
  - 8.5.0
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
install:
  - yarn install
script:
  - yarn eslint
  - yarn run coverage
  - codeclimate-test-reporter < coverage/lcov.info
